------------------------------------------------------------------------
-- Xiyan Liu & Jun Hu
-- http://www.cs.columbia.edu/~biliris/4111/17s/projects/proj1-2.html
-- Interesting queries scripts for Project1, Part2.
------------------------------------------------------------------------